### ISSUE TITLE
0 $AVAX in balance and some NFT are not available if there is more than 1024 UTXO for an address

### ISSUE THREAD

**Issue by fenicks** [ava-labs/avalanchego#524]
**Describe the bug**
After minting more than 1024 NFT, the balance decreases to zero even if there is $AVAX and all NFT disappears except 1 in the wallet.

**To Reproduce**
Create more than 1024 UTXO in wallet or create an NFTAsset with more than 1024 minters in minterSets entry.

**Expected behavior**
Having the correct $AVAX balance in wallet and all the NFT available in wallet even if there is more than 1024 UTXO.

**Screenshots**
None

**Operating System**
Ubuntu 18.04.

**Additional context**
Nothing

By submitting this issue I agree to the [Terms and Conditions](https://files.avalabs.org/legal/bug_hunt_q2_2020_terms.pdf) of the [Developer Accelerator Program](https://avalabs.org/dap).

**Comment by danlaine** [comment]
Hi @fenicks thanks for reporting.
I'm pretty sure this issue has to do with the fact that `getUTXOs` returns at most 1024 UTXOs in a single call.
@kanatliemre Can you please look into using pagination on the wallet side to fix this?

**Comment by aaronbuchwald** [comment]
This issue also impacts the Send API on the node when there are more than 1024 UTXOs, so we'll need to address this on the node as well.

**Comment by danlaine** [comment]
@fenicks This should be resolved now because of a wallet update. Can you confirm?

**Comment by fenicks** [comment]
@danlaine The web wallet is OK but the keystore API on node is not fixed.

**Comment by fenicks** [comment]
@danlaine of course.
Based on this address on mainnet : X-avax1u5rqkp3xh3kqh0apfdj8r63xh8xxsxn5sery4u
The balance is xxx, but when using the keystore JSON RPC API, the response is 0 $AVAX.

Behaviour:
```
christian@y510p:~/workspace/avalanchego$ curl -X POST --data '{
>   "jsonrpc":"2.0",
>   "id"     : 1,
>   "method" :"avm.getBalance",
>   "params" :{
>       "address":"X-avax1u5rqkp3xh3kqh0apfdj8r63xh8xxsxn5sery4u",
>       "assetID": "AVAX"
>   }
> }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
{"jsonrpc":"2.0","result":{"balance":"0","utxoIDs":[]},"id":1}
```

Expectation
```
christian@y510p:~/workspace/avalanchego$ curl -X POST --data '{
  "jsonrpc":"2.0",
  "id"     : 1,
  "method" :"avm.getBalance",
  "params" :{
      "address":"X-avax1u5rqkp3xh3kqh0apfdj8r63xh8xxsxn5sery4u",
      "assetID": "AVAX"
  }
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
{"jsonrpc":"2.0","result":{"balance":"970000000","utxoIDs":[{"txID":"7qgHCDiq8QKBN4PQvMJafYLn6pwa2utio92RSqa9jJMz6atcq","outputIndex":0}]},"id":1}
```

**Comment by danlaine** [comment]
@otherview is working on a fix for this now
